variable "public_key" {
  type = string
  default = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7tIdGhosg7/ChZKQdrEnVa7DbhidDMSg5uARCjh+LuaTyRwFci27BIKzG54WsLlfq2JWjm+i2PlXtDzGh9QWhV8maAB4McYRUyJaPCGwAlMLdSh9GgA0CCvg5mRU9H4ljGXKJk7dYvl+S7xwKFI9tYttrhRjdAsd4MI4O9pUe40yUh/ois3/Psb2U9gK9/Se5tN/wKfbW3t9iPA6+Q0ymdW5YMHez75L0c9wsa59iG5bO/veQ8gmNOSImqyDi/3BNhOgi9W6LsY1j9AZ5zFyNzqC3CftymoqhuU/F7tvkP0UG/khdkoVAvTFxDl6Wt1yy1jbAT7ZyraKKC9g9R34J Generated By Termius"
}

variable "avail_zone" {
  type = string
  default = "us-east-1a"
}

variable "vpc_ep_svc_name" {
  type = string
  default = "com.amazonaws.us-east-1.s3"
}

variable "config-NetworkMiner" {
  default = "NetworkMiner.desktop"
}

variable "config-45-allow-colord" {
  default = "45-allow-colord.sh"
}
